// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOUzipcKLVmMGrVbwpIgobmWTmi-XiT8U',
    appId: '1:42615857067:web:e94c4233303f83c447fcee',
    messagingSenderId: '42615857067',
    projectId: 'moodle-ceda9',
    authDomain: 'moodle-ceda9.firebaseapp.com',
    storageBucket: 'moodle-ceda9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOGUXJr_PVIbFZb8593APkkMVze5oNOfU',
    appId: '1:42615857067:android:190accde2017d9db47fcee',
    messagingSenderId: '42615857067',
    projectId: 'moodle-ceda9',
    storageBucket: 'moodle-ceda9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnf144rTeFEFxaym-5Fnr1pSvbW_DvYUc',
    appId: '1:42615857067:ios:8378e79d52aeed2547fcee',
    messagingSenderId: '42615857067',
    projectId: 'moodle-ceda9',
    storageBucket: 'moodle-ceda9.appspot.com',
    iosClientId: '42615857067-h215pipv5mu6q3mvej6mt3e6etm8hml8.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnf144rTeFEFxaym-5Fnr1pSvbW_DvYUc',
    appId: '1:42615857067:ios:6b66ad9bc8f839ce47fcee',
    messagingSenderId: '42615857067',
    projectId: 'moodle-ceda9',
    storageBucket: 'moodle-ceda9.appspot.com',
    iosClientId: '42615857067-2pr44aqg2abcp5ufs0aosgng7vg5jd4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodle.RunnerTests',
  );
}
